### ISSUE TITLE
warning: rb_safe_level will be removed in Ruby 3.0

### ISSUE THREAD

**Issue by simon04** [typhoeus/ethon#163]
Ruby 2.7.0 generates many warnings:

```
/home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/ethon-0.12.0/lib/ethon/curls/options.rb:103: warning: rb_safe_level will be removed in Ruby 3.0
/home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/ethon-0.12.0/lib/ethon/curls/options.rb:103: warning: rb_safe_level will be removed in Ruby 3.0
/home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/ethon-0.12.0/lib/ethon/easy/header.rb:27: warning: rb_safe_level will be removed in Ruby 3.0
/home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/ethon-0.12.0/lib/ethon/easy/header.rb:27: warning: rb_safe_level will be removed in Ruby 3.0
/home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/ethon-0.12.0/lib/ethon/curls/options.rb:103: warning: rb_safe_level will be removed in Ruby 3.0
```

**Comment by maxxsnake** [comment]
Appears the issue stems from an older version of a dependency. Running`bundle update ffi` should solve this - I was using `ffi (1.9.18)` and receiving the warning but no longer am with `ffi (1.12.2)`.

**Comment by Kjarrigan** [comment]
as @maxxsnake already said this is a warning triggered by `ffi` and not ethon. Thus closing.

**Comment by TrigonaMinima** [comment]
Not related to this issue, but anyone who is still getting these errors after updating the `ffi`, just run `bundle update --all` and all the errors should disappear.
